
export const dashboardQuotes = [
    "The secret of getting ahead is getting started. - Mark Twain",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "It's not the load that breaks you down, it's the way you carry it. - Lou Holtz",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "Well begun is half done. - Aristotle",
    "An ounce of prevention is worth a pound of cure. - Benjamin Franklin",
    "Your future is created by what you do today, not tomorrow. - Robert Kiyosaki",
    "Success is the sum of small efforts, repeated day-in and day-out. - Robert Collier",
    "Either you run the day, or the day runs you. - Jim Rohn",
    "The key to success is to focus on goals, not obstacles. - Unknown",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Productivity is never an accident. It is always the result of a commitment to excellence, intelligent planning, and focused effort. - Paul J. Meyer",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
];

export const tasksQuotes = [
    "The key is not to prioritize what's on your schedule, but to schedule your priorities. - Stephen Covey",
    "Action is the foundational key to all success. - Pablo Picasso",
    "Focus on being productive instead of busy. - Tim Ferriss",
    "The shortest way to do many things is to do only one thing at a time. - Sydney Smiles",
    "Until we can manage time, we can manage nothing else. - Peter Drucker",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The man who moves a mountain begins by carrying away small stones. - Confucius",
    "To think too long about doing a thing often becomes its undoing. - Eva Young",
    "Amateurs sit and wait for inspiration, the rest of us just get up and go to work. - Stephen King",
    "It is not enough to be busy... the question is: what are we busy about? - Henry David Thoreau",
    "You don't have to see the whole staircase, just take the first step. - Martin Luther King Jr.",
    "The secret to productivity is not finding more time, but making better use of the time you have. - Unknown",
    "Once you have commitment, you need the discipline and hard work to get you there. - Haile Gebrselassie",
    "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus. - Alexander Graham Bell",
    "Effective performance is preceded by painstaking preparation. - Brian Tracy",
];

export const calendarQuotes = [
    "A goal without a plan is just a wish. - Antoine de Saint-Exupéry",
    "Planning is bringing the future into the present so that you can do something about it now. - Alan Lakein",
    "If you fail to plan, you are planning to fail. - Benjamin Franklin",
    "A good plan today is better than a perfect plan tomorrow. - George S. Patton",
    "The future depends on what you do today. - Mahatma Gandhi",
    "By failing to prepare, you are preparing to fail. - Benjamin Franklin",
    "Give me six hours to chop down a tree and I will spend the first four sharpening the axe. - Abraham Lincoln",
    "Spectacular achievement is always preceded by unspectacular preparation. - Robert H. Schuller",
    "A plan is a list of actions arranged in whatever sequence is thought likely to achieve an objective. - John Argenti",
    "Let our advance worrying become advance thinking and planning. - Winston Churchill",
    "The time to repair the roof is when the sun is shining. - John F. Kennedy",
    "Without goals, and plans to reach them, you are like a ship that has set sail with no destination. - Fitzhugh Dodson",
    "Good fortune is what happens when opportunity meets with planning. - Thomas Edison",
    "The sooner you start to plan your life, the sooner you will live the life you dream of. - Hans Jorgen",
    "He who is best prepared can best serve his moment of inspiration. - Samuel Taylor Coleridge",
];
